[package]
name = "armoured_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_seq = "0.2.0"
libc = "0.2.144"
